config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ElmerCSC/elmerfem:
      branch: EOSC
      repo: https://github.com/ElmerCSC/elmerfem
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ElmerCSC/elmerfem git:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-celadon-maltese.sh
        container: qc.acc_gummy-alizarin-camel
  QC.Doc:
    repos:
      github.com/ElmerCSC/elmerfem find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-firebrick-axolotl.sh
        container: qc.doc_sickly-champagne-llama
      github.com/ElmerCSC/elmerfem git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-cerulean-fly.sh
        container: qc.doc_flabby-white-moorhen
      github.com/ElmerCSC/elmerfem markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-amethyst-uguisu.sh
        container: qc.doc_wimpy-champagne-pinscher
  QC.Lic:
    repos:
      github.com/ElmerCSC/elmerfem licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-coral-wolfhound.sh
        container: qc.lic_flimsy-wisteria-ray
  QC.Met:
    repos:
      github.com/ElmerCSC/elmerfem cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-gamboge-turtle.sh
        container: qc.met_freaky-dandelion-raccoon
  QC.Sec:
    repos:
      github.com/ElmerCSC/elmerfem bandit:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-orange-octopus.sh
        container: qc.sec_scaly-tomato-drever
  QC.Sty:
    repos:
      github.com/ElmerCSC/elmerfem flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-yellow-chin.sh
        container: qc.sty_silly-mustard-wasp
      github.com/ElmerCSC/elmerfem hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-mustard-birman.sh
        container: qc.sty_gimpy-malachite-sheepdog
      github.com/ElmerCSC/elmerfem jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ready-olive-grouse.sh
        container: qc.sty_goopy-olivine-rattlesnake
  QC.Ver:
    repos:
      github.com/ElmerCSC/elmerfem get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-green-hare.sh
        container: qc.ver_stinky-gold-octopus
timeout: 5400
