config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ElmerCSC/elmerfem:
      branch: EOSC
      repo: https://github.com/ElmerCSC/elmerfem
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ElmerCSC/elmerfem git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-harlequin-beagle.sh
        container: qc.acc_pretty-taupe-woodpecker
  QC.Doc:
    repos:
      github.com/ElmerCSC/elmerfem find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-ochre-whippet.sh
        container: qc.doc_slaphappy-peach-angelfish
      github.com/ElmerCSC/elmerfem git:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-purple-owl.sh
        container: qc.doc_tasty-smalt-mist
      github.com/ElmerCSC/elmerfem markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-razzmatazz-indri.sh
        container: qc.doc_crabby-cobalt-chimpanzee
  QC.Lic:
    repos:
      github.com/ElmerCSC/elmerfem licensee:
        commands:
        - /usr/bin/env sh .sqa/script.homey-maroon-jellyfish.sh
        container: qc.lic_gloppy-ultramarine-terrier
  QC.Met:
    repos:
      github.com/ElmerCSC/elmerfem cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.silly-lime-markhor.sh
        container: qc.met_gummy-emerald-dingo
  QC.Sec:
    repos:
      github.com/ElmerCSC/elmerfem bandit:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-azure-sloth.sh
        container: qc.sec_squeaky-maroon-cockroach
  QC.Sty:
    repos:
      github.com/ElmerCSC/elmerfem flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-tomato-lemur.sh
        container: qc.sty_foggy-chartreuse-civet
      github.com/ElmerCSC/elmerfem hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-amethyst-okapi.sh
        container: qc.sty_crappy-blue-eagle
      github.com/ElmerCSC/elmerfem jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-saffron-ant.sh
        container: qc.sty_chewy-tangerine-hound
  QC.Ver:
    repos:
      github.com/ElmerCSC/elmerfem get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-linen-capuchin.sh
        container: qc.ver_baggy-orchid-gharial
timeout: 5400
