config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ElmerCSC/elmerfem:
      branch: EOSC
      repo: https://github.com/ElmerCSC/elmerfem
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ElmerCSC/elmerfem git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-ecru-lionfish.sh
        container: qc.acc_woolly-purple-zonkey
  QC.Doc:
    repos:
      github.com/ElmerCSC/elmerfem find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-black-rat.sh
        container: qc.doc_randy-orchid-discus
      github.com/ElmerCSC/elmerfem git:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-gold-albatross.sh
        container: qc.doc_scanty-violet-walrus
      github.com/ElmerCSC/elmerfem markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-maroon-beetle.sh
        container: qc.doc_skimpy-chestnut-corgi
  QC.Lic:
    repos:
      github.com/ElmerCSC/elmerfem licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-copper-flamingo.sh
        container: qc.lic_skanky-green-penguin
  QC.Met:
    repos:
      github.com/ElmerCSC/elmerfem cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-alizarin-akita.sh
        container: qc.met_shaggy-pear-burmese
  QC.Sec:
    repos:
      github.com/ElmerCSC/elmerfem bandit:
        commands:
        - /usr/bin/env sh .sqa/script.randy-lemon-cockroach.sh
        container: qc.sec_gamy-auburn-squid
  QC.Sty:
    repos:
      github.com/ElmerCSC/elmerfem flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-cerise-hound.sh
        container: qc.sty_homey-purple-tuatara
      github.com/ElmerCSC/elmerfem hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-mustard-urchin.sh
        container: qc.sty_squeaky-rust-mayfly
      github.com/ElmerCSC/elmerfem jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-goldenrod-dogfish.sh
        container: qc.sty_randy-cardinal-blue
  QC.Ver:
    repos:
      github.com/ElmerCSC/elmerfem get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-razzmatazz-cockroach.sh
        container: qc.ver_lumpy-burgundy-binturong
timeout: 5400
