config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ElmerCSC/elmerfem:
      branch: EOSC
      repo: https://github.com/ElmerCSC/elmerfem
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ElmerCSC/elmerfem git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-seashell-jackal.sh
        container: qc.acc_flimsy-peach-woodpecker
  QC.Doc:
    repos:
      github.com/ElmerCSC/elmerfem find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-smalt-jackal.sh
        container: qc.doc_gloppy-white-leopard
      github.com/ElmerCSC/elmerfem git:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-chocolate-quail.sh
        container: qc.doc_skinny-mauve-forest
      github.com/ElmerCSC/elmerfem markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-pink-numbat.sh
        container: qc.doc_chummy-cardinal-kangaroo
  QC.Lic:
    repos:
      github.com/ElmerCSC/elmerfem licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-rust-impala.sh
        container: qc.lic_pokey-seashell-husky
  QC.Met:
    repos:
      github.com/ElmerCSC/elmerfem cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-khaki-molly.sh
        container: qc.met_squeaky-blue-barb
  QC.Sec:
    repos:
      github.com/ElmerCSC/elmerfem bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-denim-quokka.sh
        container: qc.sec_silly-magenta-bullfrog
  QC.Sty:
    repos:
      github.com/ElmerCSC/elmerfem flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-cerise-octopus.sh
        container: qc.sty_lovely-crimson-booby
      github.com/ElmerCSC/elmerfem hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-taupe-stoat.sh
        container: qc.sty_randy-crimson-booby
      github.com/ElmerCSC/elmerfem jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-emerald-opossum.sh
        container: qc.sty_crappy-teal-chow
  QC.Ver:
    repos:
      github.com/ElmerCSC/elmerfem get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-tan-falcon.sh
        container: qc.ver_dorky-aquamarine-emu
timeout: 5400
