config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.10
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ElmerCSC/elmerfem:
      branch: EOSC
      repo: https://github.com/ElmerCSC/elmerfem
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ElmerCSC/elmerfem git:
        commands:
        - /usr/bin/env sh .sqa/script.homely-cornflower-fousek.sh
        container: qc.acc_wheezy-black-caterpillar
  QC.Doc:
    repos:
      github.com/ElmerCSC/elmerfem find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-eggplant-mandrill.sh
        container: qc.doc_fuzzy-ecru-gar
      github.com/ElmerCSC/elmerfem git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-indigo-zonkey.sh
        container: qc.doc_baggy-apricot-mongoose
      github.com/ElmerCSC/elmerfem markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-black-stoat.sh
        container: qc.doc_grumpy-black-zebra
  QC.Lic:
    repos:
      github.com/ElmerCSC/elmerfem licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-pumpkin-warthog.sh
        container: qc.lic_stealthy-copper-coati
  QC.Met:
    repos:
      github.com/ElmerCSC/elmerfem cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-vermilion-forest.sh
        container: qc.met_woozy-gold-coral
  QC.Sec:
    repos:
      github.com/ElmerCSC/elmerfem bandit:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-teal-llama.sh
        container: qc.sec_scanty-viridian-ragdoll
  QC.Sty:
    repos:
      github.com/ElmerCSC/elmerfem flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-ultramarine-moth.sh
        container: qc.sty_cheeky-apricot-greyhound
      github.com/ElmerCSC/elmerfem hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-white-nightingale.sh
        container: qc.sty_crappy-wisteria-ferret
      github.com/ElmerCSC/elmerfem jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-lemon-zebu.sh
        container: qc.sty_seedy-emerald-skunk
  QC.Ver:
    repos:
      github.com/ElmerCSC/elmerfem get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-cinnamon-crane.sh
        container: qc.ver_gloppy-alizarin-turkey
timeout: 5400
