config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.9
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/ElmerCSC/elmerfem:
      branch: EOSC
      repo: https://github.com/ElmerCSC/elmerfem
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/ElmerCSC/elmerfem git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-salmon-moth.sh
        container: qc.acc_squeaky-malachite-sponge
  QC.Doc:
    repos:
      github.com/ElmerCSC/elmerfem find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-carmine-chow.sh
        container: qc.doc_stealthy-turquoise-anteater
      github.com/ElmerCSC/elmerfem git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-corn-liger.sh
        container: qc.doc_sleepy-corn-wildebeest
      github.com/ElmerCSC/elmerfem markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-teal-lemming.sh
        container: qc.doc_thirsty-coral-tang
  QC.Lic:
    repos:
      github.com/ElmerCSC/elmerfem licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-charcoal-dalmatian.sh
        container: qc.lic_nerdy-taupe-caracal
  QC.Sec:
    repos:
      github.com/ElmerCSC/elmerfem bandit:
        commands:
        - /usr/bin/env sh .sqa/script.surly-red-owl.sh
        container: qc.sec_paltry-black-capybara
  QC.Sty:
    repos:
      github.com/ElmerCSC/elmerfem flake8:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-teal-sloth.sh
        container: qc.sty_blurry-vermilion-dachshund
      github.com/ElmerCSC/elmerfem hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-goldenrod-okapi.sh
        container: qc.sty_snoopy-platinum-cockroach
      github.com/ElmerCSC/elmerfem jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-firebrick-maltese.sh
        container: qc.sty_snippy-firebrick-ostrich
  QC.Ver:
    repos:
      github.com/ElmerCSC/elmerfem get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-smalt-fly.sh
        container: qc.ver_thirsty-rust-alligator
timeout: 5400
